fix: fix rcmd tab dark mode gradient
BewlyBewly/BewlyBewly pull request #799
Opened 2024-05-29 14:40 UTC by shabby2333

- [x] [CONTRIBUTING](/docs/CONTRIBUTING.md)

fix issues #707 

https://github.com/BewlyBewly/BewlyBewly/assets/32442293/88b36286-7569-4e05-84e8-dba7822e82da

2024-05-29 17:58 UTC, hakadao requested changes

2024-05-30 01:01 UTC, shabby2333 commented on src/styles/adaptedStyles/videoPage.scss
> +      background: linear-gradient(270deg, var(--graph_bg_thin) 61.53%, rgba(255, 255, 255, 0) 100%);
If we don't need the shadow transform, we better to set it to `unset`.

Please do not merge this pr.
I already found a same issue left.

2024-05-30 01:04 UTC, shabby2333 commented on src/styles/adaptedStyles/videoPage.scss
> +      background: linear-gradient(270deg, var(--graph_bg_thin) 61.53%, rgba(255, 255, 255, 0) 100%);
The `linear-gradient` provides same behavior with light mode.
I think it's ok to use `unset` or `linear-gradient` .
Which solution we use, it;'s up to you.

2024-05-30 01:11 UTC, shabby2333 commented on src/styles/adaptedStyles/videoPage.scss
> +      background: linear-gradient(270deg, var(--graph_bg_thin) 61.53%, rgba(255, 255, 255, 0) 100%);
Here's preview of `unset` (the end of the video shows bilibili's original look) 



https://github.com/BewlyBewly/BewlyBewly/assets/32442293/7b0d9cc9-8050-46ae-afac-452b7312959d

2024-05-30 01:16 UTC, shabby2333 commented on src/styles/adaptedStyles/videoPage.scss
> +      background: linear-gradient(270deg, var(--graph_bg_thin) 61.53%, rgba(255, 255, 255, 0) 100%);
`var(--bew-bg)` looks like:
![image](https://github.com/BewlyBewly/BewlyBewly/assets/32442293/a3e24c41-b146-4433-9b00-084f75571f6f)

![image](https://github.com/BewlyBewly/BewlyBewly/assets/32442293/24a83bd3-cbe8-46a0-a820-99a1c9e7bde1)

2024-05-30 01:20 UTC, hakadao commented on src/styles/adaptedStyles/videoPage.scss
> +      background: linear-gradient(270deg, var(--graph_bg_thin) 61.53%, rgba(255, 255, 255, 0) 100%);
I mean using var(--bew-bg) here, instead of var(--grah-bg-thin) in linear-gradient💀

2024-05-30 01:53 UTC, merged

2024-05-30 02:05 UTC, shabby2333 commented on src/styles/adaptedStyles/videoPage.scss
> +      background: linear-gradient(270deg, var(--graph_bg_thin) 61.53%, rgba(255, 255, 255, 0) 100%);
现在的效果左侧显示会有点问题
![image](https://github.com/BewlyBewly/BewlyBewly/assets/32442293/fc46083a-ad6c-44e5-b55d-0fc09554f396)

左右需要使用不同的度数

2024-05-30 02:07 UTC, hakadao commented on src/styles/adaptedStyles/videoPage.scss
> +      background: linear-gradient(270deg, var(--graph_bg_thin) 61.53%, rgba(255, 255, 255, 0) 100%);
我其實目前並沒有看到這改變，所以之前一直沒改

2024-05-30 02:08 UTC, shabby2333 commented on src/styles/adaptedStyles/videoPage.scss
> +      background: linear-gradient(270deg, var(--graph_bg_thin) 61.53%, rgba(255, 255, 255, 0) 100%);
这样效果比较符合预期

```css
    .rcmd-tab-switcher .rcmd-tab-move.right .rcmd-tab-move-inner {
      background: linear-gradient(270deg, var(--bew-bg) 61.53%, transparent 100%);
    }
    .rcmd-tab-switcher .rcmd-tab-move.left .rcmd-tab-move-inner {
      background: linear-gradient(90deg, var(--bew-bg) 61.53%, transparent 100%);
    }
```